# Generated by Django 5.2.11 on 2026-04-09 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_veterinarian_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motivo de hospitalización')),
                ('initial_diagnosis', models.TextField(verbose_name='Diagnóstico inicial')),
                ('admission_date', models.DateTimeField(verbose_name='Fecha y hora de ingreso')),
                ('discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de alta')),
                ('patient_status', models.CharField(choices=[('critical', 'Crítico'), ('serious', 'Grave'), ('stable', 'Estable'), ('improving', 'Mejorando'), ('good', 'Bueno')], default='stable', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('discharged', 'Alta médica'), ('transferred', 'Transferida'), ('deceased', 'Fallecida')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notas generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='booking.pet')),
                ('veterinarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizations', to='booking.veterinarian')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='HospitalizationMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (lpm)')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria (rpm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('general_status', models.CharField(choices=[('critical', 'Crítico'), ('serious', 'Grave'), ('stable', 'Estable'), ('improving', 'Mejorando'), ('good', 'Bueno')], default='stable', max_length=20)),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='booking.hospitalization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalizationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluid_therapy', models.BooleanField(default=False, verbose_name='Fluidoterapia')),
                ('fluid_therapy_detail', models.CharField(blank=True, max_length=200, verbose_name='Detalle fluidoterapia')),
                ('diet', models.CharField(choices=[('normal', 'Normal'), ('soft', 'Blanda'), ('liquid', 'Líquida'), ('fasting', 'Ayuno'), ('special', 'Especial')], default='normal', max_length=20)),
                ('diet_notes', models.TextField(blank=True, verbose_name='Notas de dieta')),
                ('laboratory', models.BooleanField(default=False, verbose_name='Laboratorio')),
                ('laboratory_detail', models.TextField(blank=True)),
                ('xray', models.BooleanField(default=False, verbose_name='Rayos X')),
                ('xray_detail', models.CharField(blank=True, max_length=200)),
                ('ultrasound', models.BooleanField(default=False, verbose_name='Ultrasonido')),
                ('ultrasound_detail', models.CharField(blank=True, max_length=200)),
                ('special_instructions', models.TextField(blank=True, verbose_name='Indicaciones especiales')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitalization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_order', to='booking.hospitalization')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalizationTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('dose', models.CharField(max_length=100, verbose_name='Dosis')),
                ('frequency', models.CharField(max_length=100, verbose_name='Frecuencia')),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenosa'), ('im', 'Intramuscular'), ('sc', 'Subcutánea'), ('topical', 'Tópica'), ('other', 'Otra')], default='oral', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido'), ('completed', 'Completado')], default='active', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='booking.hospitalization')),
            ],
        ),
    ]
