# Generated by Django 5.2.11 on 2026-04-16 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_hospitalization_hospitalizationmonitoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.veterinarian'),
        ),
    ]
